#!/bin/bash

set -e

root_dirs="Demos Atmos_Originals TvShows 5D4 Music"
cinema_dirs="Movies KidsMovies HindiMovies"

SRC_ROOT="/mnt/remotes/BADAGODAAM_media"
DST_ROOT="/mnt/user/media"
# run_mode="--dry-run"
run_mode="--mirror"

for dir_name in $root_dirs
do
  echo "synchronizing $dir_name"
  /mnt/user/scripts/mirror.sh $run_mode --src ${SRC_ROOT}/${dir_name} --dest ${DST_ROOT}
  echo "==================================="
done

for dir_name in $cinema_dirs
do
  echo "synchronizing Cinema/$dir_name"
  /mnt/user/scripts/mirror.sh $run_mode --src ${SRC_ROOT}/${dir_name} --dest ${DST_ROOT}/Cinema
  echo "==================================="
done
