ui:
  title: Gatus
  header: Jaagte Raho ...
  description: Monitoring & Alerting @ Home

storage:
  type: sqlite
  path: /config/data.db
  caching: true

alerting:
  discord:
    webhook-url: "https://discord.com/api/webhooks/{{ gatus_discord_webhook }}"

webapp: &webapp
  enabled: true
  group: apps
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 200"
  alerts:
    - type: discord
      description: "healthcheck failed"
      send-on-resolved: true

domain: &domain
  group: x-domain
  interval: 24h
  conditions:
    - "[DOMAIN_EXPIRATION] > 480h"  # 20 days
  alerts:
    - type: discord
      description: "domain expiry alert"
      send-on-resolved: true
      failure-threshold: 1

endpoints:
  # network
  - name: pfsense-ui
    <<: *webapp
    group: infra
    url: "http://192.168.1.1:88"

  - name: godaam-kvm
    <<: *webapp
    group: infra
    url: https://godaam-kvm.app.apandey.com/

  # IoT
  - name: home assistant
    <<: *webapp
    group: iot
    url: "http://192.168.1.50:8123/manifest.json"

  - name: zigbee coordinator
    <<: *webapp
    group: iot
    url: "http://192.168.90.10"

  - name: zigbee2mqtt
    <<: *webapp
    group: iot
    url: "http://192.168.1.53:9442"

  # apps
  - name: nextcloud
    <<: *webapp
    url: https://cloud.app.apandey.com/status.php
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"
      - "[CERTIFICATE_EXPIRATION] > 480h"
    
  - name: willow-app-server
    <<: *webapp
    url: http://192.168.1.56:8502/api/status?type=asyncio_tasks
  - name: willow-interface-server
    <<: *webapp
    url: http://192.168.1.55:19001/api/ping
  - name: willow-interface-server-frontend
    <<: *webapp
    url: http://192.168.1.55:19001/favicon.ico

  # domains
  - name: ashishpandey.com
    <<: *domain
    url: "https://ashishpandey.com/"
  - name: apandey.com
    <<: *domain
    url: "https://apandey.com/"
  - name: ashishp.com
    <<: *domain
    url: "https://ashishp.com/"
  - name: aditpandey.com
    <<: *domain
    url: "https://aditpandey.com/"
  - name: avikpandey.com
    <<: *domain
    url: "https://avikpandey.com/"
  - name: ashish-pragya.com
    <<: *domain
    url: "https://ashish-pragya.com/"
  