---
- name: build essentials
  apt:
    name:
      - build-essential
      - python-setuptools
      - python-pip
      - monit
    state: present
  become: yes

- name: create common dirs
  file: path={{ prefix }}/{{ item }} state=directory
  with_items:
    - src
