---
- name: Build essentials
  ansible.builtin.apt:
    name:
      - build-essential
      - python-setuptools
      - python-pip
      - monit
    state: present
  become: true

- name: Create common dirs
  ansible.builtin.file:
    path: "{{ prefix }}/{{ item }}"
    state: directory
  with_items:
    - src
