---
- name: Centos8 VM
  hosts: centos8
  gather_facts: true
  roles:
    - role: xfce
      tags: xfce

- name: Godaam
  hosts: godaam
  gather_facts: false
  roles:
    - role: godaam
      tags: godaam
