#!/bin/bash
#description=backup shares to zfs
#arrayStarted=true
#name=zfs shares backup
#clearLog=true
#noParity=true

# setup
shares="appdata backups data domains gigamac isos nextcloud photo scripts software video"
dst="/zdata/backup/"

# ensure unicode filenames are supported
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export G_FILENAME_ENCODING="@locale"
export G_BROKEN_FILENAMES="1"

name="Shares Backup"
if [ ! -d "$dst" ]; then
    /usr/local/emhttp/webGui/scripts/notify -i warning -s "Sync Failure" -d "$name: bad dest: $dst"
else
    # sync
    /usr/local/emhttp/webGui/scripts/notify -i normal -s "Sync Started" -d "$name: Backing up shares to $dst"
    for share in $shares
    do
        src="/mnt/user/$share"
        if [ ! -d "$src" ]; then
            /usr/local/emhttp/webGui/scripts/notify -i warning -s "Sync Failure" -d "$name: bad source: $src"
        else
            echo "Sync ($share): $src => $dst"

            rsync --archive --verbose --delete $src $dst
            if [[ $? -eq 0 ]]; then
                /usr/local/emhttp/webGui/scripts/notify -i normal -s "Sync Complete" -d "$name: Synchronized $share successfully"
            else 
                /usr/local/emhttp/webGui/scripts/notify -i warning -s "Sync failed" -d "$name: Error. Failed to synchronize $share"
            fi
        fi
    done
fi

# snapshot the zfs backup dataset
snap="zdata/backup@$(date +%Y%m%d-%H%M%S)"
zfs snapshot -r ${snap}
if ($? != 0) then
    /usr/local/emhttp/webGui/scripts/notify -i warning -s "ZFS Snapshot" -d "failed ${snap}"
    exit 13
else
    /usr/local/emhttp/webGui/scripts/notify -i normal -s "ZFS Snapshot" -d "created ${snap}"
fi
