---
- name: get lwrf-controller source
  unarchive:
    src: https://github.com/ashishpandey/pi-lwrf-ctrl-hub/archive/master.zip
    dest: "{{ prefix }}/src"
    remote_src: yes

- name: install lwrf-controller dependencies
  pip:
    requirements: "{{ prefix }}/src/pi-lwrf-ctrl-hub-master/requirements"
    umask: "0022"
  become: yes

- include_tasks: lwrfctl.yml
  loop: "{{ lwrf_dimmers|flatten(levels=1) }}"
  loop_control:
    loop_var: lwrf_dimmer_id
