---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Bookmarks

- Docker:
    - WebUIs:
        - abbr: UI
          href: http://192.168.1.215:1111

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/ashishpandey

- Social:
    - Discord:
        - abbr: DC
          href: https://discord.com/channels/1055681497023135764/1055681534029480017

