---
# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- Media:
  - Emby:
      icon: emby.png
      href: http://192.168.1.215:8096
      description: Movies & TV Shows
      server: my-docker
      container: emby
      widget:
          type: emby
          url: http://192.168.1.215:8096
          key: "{{ emby_api_key }}"

  - Sonarr:
      icon: sonarr.png
      href: http://192.168.1.215:8989
      server: my-docker
      container: binhex-sonarr
      widget:
          type: sonarr
          fields: ["wanted", "queued", "missing"]
          url: http://192.168.1.215:8989
          key: "{{ sonarr_api_key }}"

  - Radarr:
      icon: radarr.png
      href: http://192.168.1.215:7878
      server: my-docker
      container: binhex-radarr
      widget:
          type: radarr
          fields: ["wanted", "queued", "missing"]
          url: http://192.168.1.215:7878
          key: "{{ radarr_api_key }}"

  - Prowlarr:
      icon: prowlarr.png
      href: http://192.168.1.215:9696
      server: my-docker
      container: binhex-prowlarr
      widget:
          type: prowlarr
          fields: ["enableIndexers", "numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]
          url: http://192.168.1.215:9696
          key: "{{ prowlarr_api_key }}"        

- Data:
  - "syncthing @ unraid":
      icon: syncthing.png
      href: http://192.168.1.215:8384
      server: my-docker
      container: syncthing
  - "syncthing @ talkies":
      icon: syncthing.png
      href: http://192.168.1.132:8384
      ping: https://192.168.1.132:8384/rest/noauth/health
  - "syncthing @ gigamac":
      icon: syncthing.png
      href: http://192.168.1.105:8384
      ping: http://192.168.1.105:8384/rest/noauth/health
  - paperless:
      icon: paperless-ng.png
      href: http://192.168.1.215:8000
      server: my-docker
      container: paperless-ngx
      widget:
        type: paperlessngx
        url: http://192.168.1.215:8000
        username: viewer
        password: "{{ paperless_password }}"

- Network:
  - PiHole:
      icon: pihole.png
      href: http://192.168.1.18
      server: my-docker
      container: pihole
      widget:
        type: pihole
        fields: ["queries", "blocked", "gravity"]
        url: https://pihole.app.apandey.com
        key: {{ pihole_api_key }}

  - Transmission:
      icon: transmission.png
      href: http://192.168.1.215:9091
      server: my-docker
      container: Transmission_VPN
      widget:
          type: transmission
          fields: ["leech", "seed", "download", "upload"]
          url: http://192.168.1.215:9091
        
  - Unifi:
      icon: unifi.png
      href: https://unifi.app.apandey.com
      server: my-docker
      container: unifi-controller
      widget:
        type: unifi
        fields: ["uptime", "wan", "lan_users", "wlan_users"]
        url: https://unifi.app.apandey.com
        username: admin
        password: "{{ unifi_password }}"
