---  
- name: ensure scripts
  file:
    path: /mnt/user/scripts
    state: directory
    mode: '0777'
    owner: nobody
    group: users

- name: copy mirror script
  copy:
    src: scripts/mirror.sh
    dest: /mnt/user/scripts/mirror.sh
    mode: '0555'
    owner: nobody
    group: users

- name: copy sync script
  copy:
    src: scripts/sync.sh
    dest: /mnt/user/scripts/sync.sh
    mode: '0555'
    owner: nobody
    group: users

- name: copy zfs script
  copy:
    src: scripts/zfs_prune_snapshots.sh
    dest: /mnt/user/scripts/zfs_prune_snapshots.sh
    mode: '0555'
    owner: nobody
    group: users

- include_tasks: plugin_file.yaml
  vars: 
    file: plugins/dynamix.system.temp/sensors.conf

- include_tasks: plugin_file.yaml
  vars: 
    file: plugins/theme.engine/custom.css

- name: install user scripts
  include_tasks: plugin_file.yaml
  vars: 
    file: plugins/user.scripts/scripts/{{item}}/script
  loop:
    - backup-media
    - check-docker
    - test-print
    - zbackup
    - zscrub

- name: homepage app
  import_tasks: template_dir.yaml
  vars:
    template_src: appdata/homepage
    template_dest: /mnt/user/appdata
  tags:
    - homepage
    - app

- name: gatus app
  import_tasks: template_dir.yaml
  vars:
    template_src: appdata/gatus
    template_dest: /mnt/user/appdata
  tags:
    - gatus
    - app

- name: setup sensors
  ansible.builtin.blockinfile:
    path: /boot/config/go
    marker: "######## {mark} SENSORS SETUP ########"
    block: |
      # modprobe for each sensor
      modprobe nct6775
      modprobe coretemp
      /usr/bin/sensors -s

- name: setup filesystems
  ansible.builtin.blockinfile:
    path: /boot/config/go
    marker: "######## {mark} FILESYSTEMS SETUP ########"
    block: |
      # bigger tmpfs
      mount -o remount,size=256M /var/log

      # zfs ARC allocation
      echo "#Adjusting ARC memory usage (limit 16GB)"
      echo 17179869184 > /sys/module/zfs/parameters/zfs_arc_max
