---  
- name: ensure scripts
  file:
    path: /mnt/user/scripts
    state: directory
    mode: '0777'
    owner: nobody
    group: users

- name: copy mirror script
  copy:
    src: scripts/mirror.sh
    dest: /mnt/user/scripts/mirror.sh
    mode: '0555'
    owner: nobody
    group: users

- name: copy rclone sync scans script
  copy:
    src: scripts/rclone_sync_scans.sh
    dest: /mnt/user/scripts/rclone_sync_scans.sh
    mode: '0555'
    owner: nobody
    group: users

- name: copy rclone sync gdocs script
  copy:
    src: scripts/rclone_gdocs.sh
    dest: /mnt/user/scripts/rclone_gdocs.sh
    mode: '0555'
    owner: nobody
    group: users

- name: copy sync script
  copy:
    src: scripts/sync.sh
    dest: /mnt/user/scripts/sync.sh
    mode: '0555'
    owner: nobody
    group: users

- name: copy zfs script
  copy:
    src: scripts/zfs_prune_snapshots.sh
    dest: /mnt/user/scripts/zfs_prune_snapshots.sh
    mode: '0555'
    owner: nobody
    group: users

- include_tasks: plugin_file.yaml
  vars: 
    file: plugins/dynamix.system.temp/sensors.conf

- include_tasks: plugin_file.yaml
  vars: 
    file: plugins/theme.engine/custom.css

- name: install user scripts
  include_tasks: plugin_file.yaml
  vars: 
    file: plugins/user.scripts/scripts/{{item}}/script
  loop:
    - backup-media
    - check-docker
    - test-print
    - zbackup
    - zscrub

- name: homepage app
  import_tasks: template_dir.yaml
  vars:
    template_src: appdata/homepage
    template_dest: /mnt/user/appdata
  tags:
    - homepage
    - app

- name: gatus app
  import_tasks: template_dir.yaml
  vars:
    template_src: appdata/gatus
    template_dest: /mnt/user/appdata
  tags:
    - gatus
    - app

- name: setup sensors
  ansible.builtin.blockinfile:
    path: /boot/config/go
    marker: "######## {mark} SENSORS SETUP ########"
    block: |
      # modprobe for each sensor
      modprobe nct6775
      modprobe coretemp
      /usr/bin/sensors -s

- name: setup filesystems
  ansible.builtin.blockinfile:
    path: /boot/config/go
    marker: "######## {mark} FILESYSTEMS SETUP ########"
    block: |
      # bigger tmpfs
      mount -o remount,size=256M /var/log

      # zfs ARC allocation
      echo "#Adjusting ARC memory usage (limit 16GB)"
      echo 17179869184 > /sys/module/zfs/parameters/zfs_arc_max

# - name: willow interface server files
#   unarchive:
#     src: https://github.com/toverainc/willow-inference-server/tarball/8f0d637
#     dest: /mnt/user/appdata/willow-interface-server
#     remote_src: yes
#     extra_opts:
#       - --strip-components=1 
#       - toverainc-willow-inference-server-8f0d637/nginx
#       - toverainc-willow-inference-server-8f0d637/utils.sh
#     mode: '0777'
#     owner: nobody
#     group: users
#   tags:
#     - willow
#     - app

# - name: wis nginx app
#   import_tasks: template_dir.yaml
#   vars:
#     template_src: appdata/willow-interface-server
#     template_dest: /mnt/user/appdata
#   tags:
#     - willow
#     - app

- name: traefik config
  import_tasks: template_dir.yaml
  vars:
    template_src: appdata/traefik
    template_dest: /mnt/cache/appdata
  tags:
    - traefik
    - app

- name: homepage app
  import_tasks: compose_patch.yaml
  tags:
    - compose
    - compose.patch

- name: create compose directory structure
  file:
    path: /boot/config/plugins/compose.manager/projects/{{ item.path }}
    state: directory
    mode: '0700'
  with_filetree: ../templates/plugins/compose.manager/projects/
  loop_control:
    label: '{{item.path}}'
  when: item.state == 'directory'
  tags:
    - compose

- name: deploy compose files
  template:
    src: "{{ item.src }}"
    dest: /boot/config/plugins/compose.manager/projects/{{ item.path }}
    mode: '0600'
  with_filetree: ../templates/plugins/compose.manager/projects/
  loop_control:
    label: '{{item.path}}'
  when: item.state == 'file'
  tags:
    - compose

- name: deploy esphome secrets
  template:
    src: esphome/secrets.yaml
    dest: /mnt/user/appdata/esphome/config/secrets.yaml
    mode: '0666'
  tags:
    - esphome

- name: deploy esphome projects
  copy:
    src: esphome/
    dest: /mnt/user/appdata/esphome/config/
    mode: '0666'
  tags:
    - esphome