---
# variables
# - file: file

- name: Show message
  ansible.builtin.debug:
    msg: installing /boot/config/{{ file }}

- name: Ensure user script dir {{ file | dirname }} exists
  ansible.builtin.file:
    path: /boot/config/{{ file | dirname }}
    state: directory
    mode: "0700"
    owner: root
    group: root

- name: Copy user script {{ file }}
  ansible.builtin.copy:
    src: "{{ file }}"
    dest: /boot/config/{{ file }}
    mode: "0600"
    owner: root
    group: root
