http:
  routers:
    unraid:
      entryPoints:
      - http
      service: unraid
      rule: "Host(`unraid.app.apandey.com`)"
  services:
    unraid:
      loadBalancer:
        servers:
        - url: "http://192.168.1.215:88/"
