---
- name: Ensure scaffold
  ansible.builtin.file:
    path: /volume1/share/scaffold/bin
    state: directory
  loop:
    - /volume1/share/scaffold/bin
    - /volume1/share/scaffold/log

- name: Copy batch script
  ansible.builtin.template:
    src: batch_image_resize.sh
    dest: /volume1/share/scaffold/bin/batch_image_resize.sh
    mode: "0755"

- name: Copy backup script
  ansible.builtin.template:
    src: backup_volume2.sh
    dest: /volume1/share/scaffold/bin/backup_volume2.sh
    mode: "0755"
